### ISSUE TITLE
✨ Functionality: Add OG tags for social sharing

### ISSUE THREAD

**Issue by JoseeWouters** [fronteers/website#10]
## Description
Every page should have the correct OG tags for social sharing, at least for images, title and description on Facebook, Twitter and LinkedIn.

## Why should we include this?
To improve the way the pages look when shared on social media.

**Comment by banaan666** [comment]
This seems to have already been added to src/_includes/partials/utility/html-head.liquid

**Comment by edwinm** [comment]
Meta tags are added, but don't contain relevant information.

The description and image should be depended on the page you're viewing.

**Comment by edwinm** [comment]
Remove superfluous and deprecated meta tags, add og:image tags
Feature/og tags #247
