### ISSUE TITLE
Problem in attaching the shortcodes CSS file to the website style

### ISSUE THREAD

**Issue by iflashlord** [fronteers/website#105]
**Describe the bug**
We can have two files for any shortcode one .js and one .css, the problem is the .css file does not attach to the website style on serve, hence if we put anything in the CSS file it has not resulted.
I have checked the configuration but I could not find an appropriate way to force to attach these styles.

**To Reproduce**
1. Go to any of shortcodes CSS file and add any style
2. Serve
3. Check the style file or result has not applied

**Expected behavior**
We expect to attach CSS files regarding the shortcode and component to attach the website style.
suggestion: make isolation style for shortcodes not to have conflict with other shortcodes or styles.

**Comment by anneke** [comment]
Hi Behrouz, I have looked into this (I'm sorry it took me this long) but made sure it's being read and watched (at least the css) in this PR: https://github.com/fronteers/website/pull/109 :)
