### ISSUE TITLE
Create development run command with sample data

### ISSUE THREAD

**Issue by anneke** [fronteers/website#129]
## Description
Create a build command for development dat only processes part of the markdown files into webpages. 

## Why should we include this?
Currently a `npm run dev` command takes a long time because it processes a lot of content, which makes development a little less convenient.

## Happy flow
Only process the latest 6(?) blogposts, activities, etc.

**Comment by SleeplessByte** [comment]
I don't think we need this. After merging #166 and #176, only the first build takes a minute. Any subsequent change should be done within a second.
