### ISSUE TITLE
Missing favicon

### ISSUE THREAD

**Issue by hans2103** [fronteers/website#141]
## Description
There is no favicon 

## Why should we include this?
Create favicon

I will create one using the Fronteers logo

**Comment by hans2103** [comment]
voorstel voor favicon
[favicon.svg.zip](https://github.com/fronteers/website/files/9254586/favicon.svg.zip)
<img width="1170" alt="Schermafbeelding 2022-08-03 om 21 54 51" src="https://user-images.githubusercontent.com/639822/182698029-a118a618-3f76-4b1f-82bf-6f6cc333f573.png">

**Comment by hans2103** [comment]
Bij akkoord zet ik deze middels https://realfavicongenerator.net om naar een favicon en voeg ik er een aantal zoals beschreven via https://evilmartians.com/chronicles/how-to-favicon-in-2021-six-files-that-fit-most-needs

**Comment by edwinm** [comment]
Prima

**Comment by Ninajoy** [comment]
Helemaal top!

**Comment by hans2103** [comment]
Created PR https://github.com/fronteers/website/pull/145 to add favicon

**Comment by hans2103** [comment]
PR is merged... therefor issue closed
