### ISSUE TITLE
Content overzetten

### ISSUE THREAD

**Issue by anneke** [fronteers/website#148]
## Description
Content overzetten

## Why should we include this?
Belangrijk!

## Happy flow
Als je op een tekstpagina (zoals "Over Fronteers") komt, staat daar copy op zonder gebroken links

**Comment by banaan666** [comment]
When transferring content from old to new website, keep the following in mind:

- add /nl or /en before internal links
- you can download the markdown by accessing the old URL and adding .md at the end
- non index.md files can be linked to by added .html to the link
- { % form %} causes errors in the check, not sure what to do about those 
- keep the path the same except for the thing in first bullet
- tables aren't support in the markdown export feature in QMS currently, requires some manual markdowning

**Comment by banaan666** [comment]
Onderstaande pagina's zijn overgezet, op veel van de pagina's stond een formulier onder aan de pagina.

# Done
https://fronteers.nl/vereniging/geschiedenis/statuten -> /nl/vereniging/statuten
https://fronteers.nl/vereniging/alv -> /nl/vereniging/alv 
https://fronteers.nl/vereniging/geschiedenis/namen -> /nl/vereniging/geschiedenis/namen
https://fronteers.nl/vereniging/geschiedenis -> /nl/vereniging/geschiedenis

# Doing
https://fronteers.nl/vereniging/bestuur/notulen -> /nl/vereniging/bestuur/notulen - Missing list
https://fronteers.nl/vereniging/bestuur -> /nl/vereniging/bestuur - Links
https://fronteers.nl/vereniging/commissies -> /nl/vereniging/commissies - Links
https://fronteers.nl/vereniging/belgie -> /nl/vereniging/commissies/belgie - Form
https://fronteers.nl/vereniging/commissies/congres -> /nl/vereniging/commissies/congres - Form
https://fronteers.nl/vereniging/vrijwilligers -> /nl/vereniging/vrijwilligers - Links
https://fronteers.nl/vereniging/commissies/marketing -> /nl/vereniging/commissies/marketing - Form
https://fronteers.nl/vereniging/commissies/online-community -> /nl/vereniging/commissies/online-community - Hidden | Vacturebank
https://fronteers.nl/vereniging/commissies/webrichtlijnen -> /nl/vereniging/commissies/webrichtlijnen - Form
https://fronteers.nl/vereniging/commissies/vacatures -> - /nl/vereniging/commissies/vacatures - Form
https://fronteers.nl/vereniging/commissies/workshops -> /nl/vereniging/commissies/workshops - Form
https://fronteers.nl/vereniging/commissies/incidenteel-helpende-vrijwilligers -> /nl/vereniging/commissies/incidenteel-helpende-vrijwilligers - Link
https://fronteers.nl/vereniging/vrijwilligers/bestuursleden -> /nl/vereniging/vrijwilligers/bestuursleden - Form
https://fronteers.nl/vereniging/vrijwilligers/activiteiten -> /nl/vereniging/vrijwilligers/activiteiten - Form
https://fronteers.nl/vereniging/vrijwilligers/congres -> /nl/vereniging/vrijwilligers/congres - Form
https://fronteers.nl/vereniging/vrijwilligers/vacature-commissie-website -> /nl/vereniging/vrijwilligers/vacature-commissie-website - Form
https://fronteers.nl/vereniging/vrijwilligers/workshops -> /nl/vereniging/vrijwilligers/workshops - Form
https://fronteers.nl/vereniging/lidmaatschap -> /nl/word-lid/lidmaatschap/

**Comment by anneke** [comment]
Closing issue, is ondertussen dubbel (en veel hiervan is gedaan)
