### ISSUE TITLE
🏗  Component: Content table

### ISSUE THREAD

**Issue by banaan666** [fronteers/website#150]
Some pages contain tables, these currently lack any styling. Example '/src/nl/vereniging/geschiedenis/index.md'

## Design

???

## Files to edit: 

???

## Status of the build checklist

- [ ] the design has been turned into HTML and CSS
- [ ] the CSS is well-organised and cleaned up from development
- [ ] the HTML is semantic and passes an automated accessibility test
- [ ] the component is no longer scaffolding but easy to use in the setup of other pages
- [ ] the work done is added to the `component` folder as a block or as a shortcode, if it makes sense to in future use this component within articles and running text
- [ ] the work done is represented to `src/nl/kitchensink` or `src/nl/kitchensink-html` for documentation
- [ ] the work done has been commented or is (really!) self-explanatory

**Comment by JanitaRiyaz** [comment]
i wanna do this. Assign this to me.
