### ISSUE TITLE
Netlify: End of support for Xenial build image

### ISSUE THREAD

**Issue by banaan666** [fronteers/website#156]
**Describe the bug**
Build process stopped working on the November 15, 2022, because the image used for the building process is EOL.
For more information see
https://answers.netlify.com/t/please-read-end-of-support-for-xenial-build-image-everything-you-need-to-know/68239/1

**To Reproduce**
1. Create a Pull Request
2. Scroll down and look at the Checks, all Build sets currently fail
3. Click 'Details'
4. Click 'the logs'

**Expected behavior**
All steps are Green

**Screenshots**
Console output:
11:13:39 PM: Build ready to start
11:13:39 PM: ---------------------------------------------------------------------
  UNSUPPORTED BUILD IMAGE

  The build image for this site uses Ubuntu 16.04 Xenial Xerus, which is no longer supported.

  To enable builds for this site, select a later build image at the following link:
  https://app.netlify.com/sites/fronteers-beta/settings/deploys#build-image-selection

  For more details, visit the build migration guide:
  https://answers.netlify.com/t/please-read-end-of-support-for-xenial-build-image-everything-you-need-to-know/68239
  ---------------------------------------------------------------------

**Comment by banaan666** [comment]
Can probably be fixed using the follow URL
https://app.netlify.com/sites/fronteers-beta/settings/deploys#build-image-selection

**Comment by anneke** [comment]
I tried changing it! Let's see :)

**Comment by banaan666** [comment]
Checks are running again, tested with PR #157

**Comment by banaan666** [comment]
All things are up and running again.
