### ISSUE TITLE
Copy content: Blog items december 2022 including Advent calendar 2022

### ISSUE THREAD

**Issue by anneke** [fronteers/website#169]
## Description
Copy over advent calendar news articles from 2022 from the current website into this repository.

Remember you can copy over content as markdown by adding .md at the end of the URL:
To get the markdown of `https://fronteers.nl/vereniging` -> : `https://fronteers.nl/vereniging.md`

**Comment by Ninajoy** [comment]
Migrated first blog https://fronteers.nl/blog/2022/12/herfstblaadjes-zien. I will proceed with second oldest (old to new)

Peter will proceed with blogs from December 1st and newer.

**Comment by anneke** [comment]
@peterdoolaard Do you have any uncommitted updates to this?
