### ISSUE TITLE
Add GitHub action to test for broken URLs

### ISSUE THREAD

**Issue by anneke** [fronteers/website#172]
## Description
We want to redirect properly to the right (new) URL's from within articles that might link to the old website structure. According to @SleeplessByte we can do this with a GitHub action :)

**Comment by edwinm** [comment]
Update  `/_redirects` file.

**Comment by anneke** [comment]
Added a plugin:

https://github.com/bradleyburgess/eleventy-plugin-broken-links?tab=readme-ov-file#1-install-the-plugin

See https://github.com/fronteers/website/pull/302
