### ISSUE TITLE
[i18n] Alternate links are incorrect

### ISSUE THREAD

**Issue by SleeplessByte** [fronteers/website#183]
**Describe the bug**

The `link rel="alternate"` that point to [translated versions of the content](https://developers.google.com/search/docs/specialty/international/localized-versions) are incorrectly implemented.

**To Reproduce**
1. Go to any page
2. Inspect the `html`

**Expected behavior**

- Alternate links are _fully qualified_, which means `https://domain.tld/full/localized/path` 
- Alternate links link to the actual page, not some directory structute
- Alternate links are not present if the content does not exist

**Comment by edwinm** [comment]
Removing code below since it's not correct.

```
    {%- for language in site.languages -%}
        <link rel="alternate" hreflang="{{ language.hreflang }}" href="/{{ language.code }}/" />
    {%- endfor -%}
```

If we make this, it should also be used in the language selector.

Anneken made a script to find a page in the other language, which was removed to improve build times.

**Comment by edwinm** [comment]
Created new ticket to fix this correctly.

"Language toggle should keep the page subject" #249
