### ISSUE TITLE
Desktop menu does not work with touch navigation

### ISSUE THREAD

**Issue by SleeplessByte** [fronteers/website#184]
**Describe the bug**
When using the website on a desktop with touch navigation, it is not possible to open the dropdowns, thus it's not possible to reach all the content.

**To Reproduce**
1. Go to the website
2. Use a touch screen (hint: mobile device with desktop view, or simulate it via devtools)
3. Try to open the dropdown menu

**Expected behavior**

We can detect if there is a pointer as the "main" way to navigate, and if so, we can change the behaviour. However, it may be better to "just" change the top link to not be a link, but a button instead.

**Comment by edwinm** [comment]
Fixed
