### ISSUE TITLE
Footer is squished on "tablets"

### ISSUE THREAD

**Issue by SleeplessByte** [fronteers/website#185]
**Describe the bug**
Exactly as title

**To Reproduce**
1. Go to any page
2. Resize the window to 768px
3. See screenshot

**Expected behavior**
It doesn't look squished.

**Screenshots**
![fronteers-beta netlify app_nl_blog_2022_04_fronteers-is-op-zoek-naar-nieuwe-bestuursleden html](https://user-images.githubusercontent.com/1964376/213871211-fbf5bffe-64bf-4c55-96f1-9a7c1c9753c9.png)

Note that the right most column is cut-off as well.

**Comment by Sahad-09** [comment]
Hey i would like to work on this
