### ISSUE TITLE
Formulier: Vacaturebank

### ISSUE THREAD

**Issue by banaan666** [fronteers/website#188]
## Description
https://fronteers.nl/vacaturebank/vacature-toevoegen

E-mail die verstuurd wordt:
From: Afdeling Backoffice (via Fronteers) <info@fronteers.nl>
Date: Thu, Oct 6, 2022 at 4:47 PM
Subject: Ik wil een vacature plaatsen (fronteers.nl, 06-10-2022, 16:47:29)
To: <vacaturebank@fronteers.nl>

Contactpersoon: 	Afdeling Backoffice
E-mailadres contactpersoon: 	peno@fronteers.nl
Telefoonnummer: 	0132342345
Bedrijfsnaam: 	Fronteers B.V.
Factuuradres: 	Straatlaan 22, 1234AB, Frontcity
E-mailadres voor de factuur: 	crediteuren@fronteers.nl
Uw kenmerk: 	1234567
Dienstverband of freelance: 	Dienstverband
Akkoord met bovenstaande voorwaarden: 	Ja

Op 06-10-2022 om 16:47:29 uur ingevuld op https://fronteers.nl/vacaturebank/vacature-toevoegen, via https://fronteers.nl/vacaturebank/vacature-toevoegen

More information is needed.

**Comment by banaan666** [comment]
Navraag gedaan bij de vacaturebank beheerder voor een voorbeeld e-mail.

**Comment by anneke** [comment]
Workaround voor MLP: een mailto: link met de content pre-filled. See https://www.sender.net/mailto-link-generator/

**Comment by anneke** [comment]
```
[Ik wil een vacature plaatsen]
Contactpersoon [f text]
E-mailadres contactpersoon [a text]
Telefoonnummer [_ text]
Bedrijfsnaam [_ text]
Twitter-account bedrijf _optioneel_ [_ text]
Factuuradres [+ small]
E-mailadres voor de factuur [_ text]
Uw kenmerk _optioneel, bijvoorbeeld een inkoopnummer_ [_ text]
Dienstverband of freelance? [o Dienstverband|Freelance]
Akkoord met bovenstaande voorwaarden? [o Ja|Nee]
Eventuele opmerkingen of vragen [+ small]
[Verstuur](vacaturebank@fronteers.nl;melding:Bedankt voor je aanvraag! We nemen *zo spoedig mogelijk* contact met je op. Onze vereniging *draait echter op vrijwilligers*, houd er dus rekening mee dat een reactie niet altijd dezelfde dag komt, en het in drukke periodes zelfs een week kan duren.)
```

dit is het formulier zoals het op de huidige site staat!
