### ISSUE TITLE
[question] Hide content older than X years, archive old site?

### ISSUE THREAD

**Issue by anneke** [fronteers/website#189]

**Comment by anneke** [comment]
Suggestion to hide content from before 2018, and maybe render a different summary of event hosts from the old site to reflect all the things we've done in the past

**Comment by banaan666** [comment]
https://fronteers.nl has been crawled 26-01-2023, the browsable copy has been stored in Stack Storage. Around 20,5GB which is mostly video files.

I will also upload some separate .zip-files with only the images/pages used in the website.
