### ISSUE TITLE
Formatting blog posts

### ISSUE THREAD

**Issue by peterdoolaard** [fronteers/website#196]
Blog post content lacks some formatting:
- [x] images are not responsive (see: #177)
- [x] non-decorative images should be figure with possibly figcaption 
- [x] font size of lists is too small
- [x] block quotes lack formatting 
- ...

**Comment by michaelhastrich** [comment]
@peterdoolaard heb je een url van een post waar de list-items in een te kleine fornt-size worden gezet? [Hier](http://localhost:8080/nl/blog/2022/12/zure-developers-uitnodigende-communicatie.html) (zie screenshot) staan ze volgens mij goed, namelijk
<img width="795" alt="Screenshot 2023-03-31 at 08 53 51" src="https://user-images.githubusercontent.com/754066/229045711-ea800b54-c8f7-4220-82bf-94b2ac4da8a1.png">

**Comment by peterdoolaard** [comment]
@michaelhastrich Ik kan geen voorbeelden (meer) vinden van een afwijkende font-size
