### ISSUE TITLE
[i18n] Categories: categories list should be corresponding to NL/EN versions

### ISSUE THREAD

**Issue by mserykh** [fronteers/website#198]
**Describe the bug**
Pages with filters (jobs, activities, blogs) for both versions (NL, EN) have the same list of filters. 

**To Reproduce**
1. Go to `/nl/blog`
2. See the list of the filters
3. Switch language, go to `en/blog`
4. See the list of the filters (it is the same).

**Expected behavior**
The list of filters should consist only of the used filters for the items.

**Screenshots**
NL
![nl](https://user-images.githubusercontent.com/61358937/214047025-f4395bc2-ef1b-4d1a-ad3f-f85b19c480b7.png)

EN
![en](https://user-images.githubusercontent.com/61358937/214047053-e2c1f171-2421-4310-b41f-cf07f98350dd.png)

**Comment by Schepp** [comment]
It is now fixed, in that only those tags are shown, which have been tagged into any post of the current locale/language. But I noticed that the tags are still Dutch within the English blogposts, as they were entered as such in the markdown files.
