### ISSUE TITLE
Check content

### ISSUE THREAD

**Issue by anneke** [fronteers/website#204]
For each page that is visible on the site, we need to make sure it has content (like our current website), that the links in it work correctly, that it has a proper 'header'/hero and that the design is alright.

| URL testenvironment | Page name | Content entered in | Content updated for 2023? | Design checked? |
| ------------- | --------- | --------- | --------- | ------------ |
| https://fronteers-beta.netlify.app/nl/vereniging/geschiedenis/namen/  |  Geschiedenis/namen  | ✅ | ❌ | ❌ |
| https://fronteers-beta.netlify.app/en/organisation/history/names/  |  History/names  | ✅ | ❌ | ❌ |
| https://fronteers-beta.netlify.app/nl/vereniging/statuten/  |  Statuten   | ✅ | ❌ | ❌ |
| https://fronteers-beta.netlify.app/en/organisation/statutes/  |  Statutes | ✅ | ❌ | ❌ |
| https://fronteers-beta.netlify.app/nl/word-lid/voorwaarden/  |  Voorwaarden | ✅ | ❌ | ❌ |
| https://fronteers-beta.netlify.app/nl/word-lid/lidmaatschap/  |  Lidmaatschap | ❌ | ❌ | ❌ |
| https://fronteers-beta.netlify.app/nl/word-lid/code-of-conduct/  |  Code of conduct | ❌ | ❌ | ❌ |
| https://fronteers-beta.netlify.app/nl/word-lid/  |  Word lid  | ❌ | ❌ | ❌ |
| https://fronteers-beta.netlify.app/nl/werk-en-freelance/voorwaarden/  |  Voorwaarden  | ❌ | ❌ | ❌ |
| https://fronteers-beta.netlify.app/nl/werk-en-freelance/vacature-plaatsen/  |  Vacature plaatsen  | ❌ | ❌ | ❌ |
| https://fronteers-beta.netlify.app/nl/werk-en-freelance/  |  Werk en freelance  | ❌ | ❌ | ❌ |
| https://fronteers-beta.netlify.app/nl/werk-en-freelance/freelancers  | Freelancers  | ❌ | ❌ | ❌ |
| https://fronteers-beta.netlify.app/nl/vereniging/support | Support (MLP: not needed)   | ❌ | ❌ | ❌ |
| https://fronteers-beta.netlify.app/nl/vereniging/organisatie | Organisatie (MLP: not needed)  | ❌ | ❌ | ❌ |
| https://fronteers-beta.netlify.app/nl/vereniging/geschiedenis | Geschiedenis  | ✅ | ❌ | ❌ |
| https://fronteers-beta.netlify.app/nl/vereniging/commissies | Commissies    | ✅ | ❌ | ❌ |
| https://fronteers-beta.netlify.app/nl/vereniging/bestuur | Bestuur    | ✅ | ❌ | ❌ |
| https://fronteers-beta.netlify.app/nl/vereniging/alv | Algemene Ledenvergadering  |  ✅ | ❌ | ❌ |
| https://fronteers-beta.netlify.app/nl/vereniging | Over Fronteers  |  ✅ | ❌ | ❌ |
| https://fronteers-beta.netlify.app/nl/leden/  |  Leden | ❌ | ❌ | ❌ |
| https://fronteers-beta.netlify.app/nl/footer/privacy-en-cookies/  |  Privacy & cookie statement  | ❌ | ❌ | ❌ |
| https://fronteers-beta.netlify.app/nl/footer/nieuwsbrief/  |  Nieuwsbrief  | ❌ | ❌ | ❌ |
| https://fronteers-beta.netlify.app/nl/footer/contact/  |  Contact   | ❌ | ❌ | ❌ |
| https://fronteers-beta.netlify.app/nl/footer/colofon/  |  Colofon   | ❌ | ❌ | ❌ |
| https://fronteers-beta.netlify.app/nl/footer/adverteren/  |  Adverteren| ❌ | ❌ | ❌ |
| https://fronteers-beta.netlify.app/nl/congres/  |  Congres   | ❌ | ❌ | ❌ |
| https://fronteers-beta.netlify.app/nl/blog/  |  Blog  | ❌ | ❌ | ❌ |
| https://fronteers-beta.netlify.app/nl/activiteiten/workshops/  |  Workshops | ❌ | ❌ | ❌ |
| https://fronteers-beta.netlify.app/nl/activiteiten/events/  |  Meetups   | ❌ | ❌ | ❌ |
| https://fronteers-beta.netlify.app/nl/activiteiten/  |  Activiteiten | ❌ | ❌ | ❌ |
| https://fronteers-beta.netlify.app/en/organisation/support | Support (MLP: not needed)   | ❌ | ❌ | ❌ |
| https://fronteers-beta.netlify.app/en/organisation/organisation | Organisation (MLP: not needed) | ❌ | ❌ | ❌ |
| https://fronteers-beta.netlify.app/en/organisation/members-meeting | Membership meeting | ✅ | ❌ | ❌ |
| https://fronteers-beta.netlify.app/en/organisation/history | History   | ✅ | ❌ | ❌ |
| https://fronteers-beta.netlify.app/en/organisation/committees | Committees | ✅ | ❌ | ❌ |
| https://fronteers-beta.netlify.app/en/organisation/board | Board | ✅ | ❌ | ❌ |
| https://fronteers-beta.netlify.app/en/organisation | About Fronteers | ✅ | ❌ | ❌ |
| https://fronteers-beta.netlify.app/en/members/  |  Members   | ❌ | ❌ | ❌ |
| https://fronteers-beta.netlify.app/en/join-us/terms-and-conditions/  |  Terms and conditions  | ❌ | ❌ | ❌ |
| https://fronteers-beta.netlify.app/en/join-us/membership/  |  Membership| ❌ | ❌ | ❌ |
| https://fronteers-beta.netlify.app/en/join-us/code-of-conduct/  |  Code of conduct  | ❌ | ❌ | ❌ |
| https://fronteers-beta.netlify.app/en/join-us/  |  Join us   | ❌ | ❌ | ❌ |
| https://fronteers-beta.netlify.app/en/jobs/terms-and-conditions/  |  Terms and conditions | ❌ | ❌ | ❌ |
| https://fronteers-beta.netlify.app/en/jobs/post-job-opening/  |  Post a job opening | ❌ | ❌ | ❌ |
| https://fronteers-beta.netlify.app/en/jobs/  |  Jobs  | ❌ | ❌ | ❌ |
| https://fronteers-beta.netlify.app/en/jobs/freelancers  | Freelancers  | ❌ | ❌ | ❌ |
| https://fronteers-beta.netlify.app/en/footer/privacy-and-cookies/  |  Privacy & cookie statement | ❌ | ❌ | ❌ |
| https://fronteers-beta.netlify.app/en/footer/newsletter/  |  Newsletter| ❌ | ❌ | ❌ |
| https://fronteers-beta.netlify.app/en/footer/contact/  |  Contact   | ❌ | ❌ | ❌ |
| https://fronteers-beta.netlify.app/en/footer/colophon/  |  Colophon  | ❌ | ❌ | ❌ |
| https://fronteers-beta.netlify.app/en/footer/advertise/  |  Advertise | ❌ | ❌ | ❌ |
| https://fronteers-beta.netlify.app/en/conference/  |  Conference| ❌ | ❌ | ❌ |
| https://fronteers-beta.netlify.app/en/blog/  |  Blog  | ❌ | ❌ | ❌ |
| https://fronteers-beta.netlify.app/en/activities/workshops/  |  Workshops | ❌ | ❌ | ❌ |
| https://fronteers-beta.netlify.app/en/activities/events/  |  Meetups   | ❌ | ❌ | ❌ |
| https://fronteers-beta.netlify.app/en/activities/  |  Activities  | ❌ | ❌ | ❌ |

**Comment by AnnemiekNieboer** [comment]
@anneke heb je hier hulp bij nodig?

**Comment by anneke** [comment]
@AnnemiekNieboer Ja, een vers paar ogen om even te kijken waar we content van de huidige site zouden kunnen hergebruiken zou fijn zijn :)
