### ISSUE TITLE
Page header on English pages doesn't have the correct design yet

### ISSUE THREAD

**Issue by banaan666** [fronteers/website#238]
**Describe the bug**
Page header (H2) on English pages doesn't have the banner design yet

**To Reproduce**
1. Go to [Dutch](https://fronteers-beta.netlify.app/nl/vereniging/geschiedenis/)
2. Go to [English](https://fronteers-beta.netlify.app/en/organisation/history/)

**Expected behavior**
H2 should have a nice big banner

**Screenshots**
See links.

**Comment by devbytemehedi** [comment]
yea it does.

**Comment by anneke** [comment]
I worked on it a while ago and I guess I forgot to close this issue 😅
