### ISSUE TITLE
Migrate existing content from old to new CMS

### ISSUE THREAD

**Issue by michaelhastrich** [fronteers/website#26]
The content that is now in QMS needs to be migrated to the Eleventy frontmatter format.

- [x] make briefing 
- [x] contact Krijn
- [ ] receive content, and plug it in!

**Comment by anneke** [comment]
We need to make a briefing for Krijn that summarizes the form of the front-end matter, so he can export all the content from the current website in a compatible format for us.

**Comment by anneke** [comment]
Woops, this issue got closed automatically. I have built some components that mirror components on the old website, ('content types' as they are called there), and we should now be able to download content to see if it works correctly by adding `.md` behind a link on the current site.

For example:

[https://fronteers.nl/blog/2021/01/thats-all-folks](https://fronteers.nl/blog/2021/01/thats-all-folks)

>>

[https://fronteers.nl/blog/2021/01/thats-all-folks.md](https://fronteers.nl/blog/2021/01/thats-all-folks.md)
