### ISSUE TITLE
Word lid does not have a focus style

### ISSUE THREAD

**Issue by SleeplessByte** [fronteers/website#265]
**Describe the bug**
As title

**To Reproduce**
1. Go to home page
2. Move focus to "word lid" button

**Expected behavior**
It has a focus indicator

**Screenshots**

![Focus indicator not showing on a button on the website](https://github.com/fronteers/website/assets/1964376/7d0ea1ef-8724-4d5f-b63e-dba1e2493669)

**Comment by devbytemehedi** [comment]
hey, i am beginner to contribution. so, help me . do i need to clone the whole repository because the size is huge ?

**Comment by devbytemehedi** [comment]
should i Shallow Clone the repo ?

**Comment by edwinm** [comment]
@devbytemehedi : The idea is that you clone the whole repository. The repository, including generated files, is around 550MB. I don't think you can work on it when you cloned it partially.

The site is close to getting live. Today we will mostly talk and work on things that has to be done to put the site live.

But you're welcome to pick up stories! The site is a collaborative effort.

**Comment by devbytemehedi** [comment]
Thanks for the information! I understand that cloning the entire 550MB repository is necessary to work on it properly.
