### ISSUE TITLE
Eleventy does not rebuild when partial liquid file is changed

### ISSUE THREAD

**Issue by SleeplessByte** [fronteers/website#268]
## Description
As title

## Why should we include this?
Improve DX. Currently it does refresh the CSS of a partial if it's changed. Would be great if liquid also was picked up. I could not see how to make this work with 11ty 2.0.1

**Comment by anneke** [comment]
I don't know if it's because of my update to v2.0.1., but if I make a change to a liquid partial file now, it does change the file, it just takes a looooong time. (31 seconds? `Wrote 907 files in 31.64 seconds (34.9ms each, v2.0.1)`)

**Comment by SleeplessByte** [comment]
It will take even longer on other systems, because it does a full rebuild -- which is fine tbh. The issue is sub-directories on windows. Wontfix because it's not worth the time investment.
