### ISSUE TITLE
Go through issues from Jules' website audit

### ISSUE THREAD

**Issue by anneke** [fronteers/website#273]
Expert Jules Ernst went through the website for us and wrote an audit for us. He found a few issues that we should fix before we go live.

https://www.toegankelijkheidscertificaat.nl/fronteers.nl/audit/

**Comment by maniflames** [comment]
I went through the ['issues only' version of the report](https://www.toegankelijkheidscertificaat.nl/fronteers.nl/audit/issues/) Jules created and tested each finding to see if it was still present in the latest beta of the site. Additionally, @SleeplessByte and I had a quick chat about what falls within the scope of the navigation ticket. 

A full list of todos that are covered by this ticket: 
- [ ] Navigation (#273)
    - [ ] Finding 1: (optional?) Turn names of socials in the footer into `h3` elements
    - [ ] Finding 5: Ensure selected pages in navigation submenu have an additional visual indicator for those who are colorblind
    - [x] Finding 7: The 'join us' button disappears from a 200% zoom and has no alternative
    - [x] Finding 9: The navbar doesn't allow for keyboard navigation
    - [ ] Finding 10: Ensure that the navigation at a 400% zoom doesn't disappear when transitioning from open to closed. Optionally put focus on first menu item when menu is opened.
    - [ ] Finding 12: Ensure that the navigation button at a 400% zoom has a visible focus state
    - [x] Finding 13: Ensure that the correct language is used for visually hidden text in the language switcher
    - [ ] Finding 14: (optional/not needed for WCAG 2.2 A compliance) Ensure there is only one element with the id "Icon_menu"
    - [ ] Finding 15: Ensure that spans end with an additional space in visually hidden text in the language switcher
    - [x] Finding 16: Ensure that selected pages that are linked in the footer are marked as active through aria-current
    - [ ] Finding 17: Ensure that the navigation button at a 400% zoom only has one button for opening and closing the menu. Use aria-expanded to notify the user that the menu is open or closed.
- [x] Blog overview
    - [x] Finding 2: Ensure that the header on top of the page has a heading that ensures it that contains other page content
- [ ] Hero
    - [ ] Finding 8: Ensure that text within the Hero stays visible at a 400% zoom.
- [x] Activity component
    - [x] Finding 11: Ensure that urls that are visible to screen readers have unique content 
- [ ] General markdown rendering
    - [ ] Finding 3: Ensure that the header structure of the blog detail pages is semantically accurate
    - [ ] Finding 4: Ensure data cells of tables are related to their heading by adding the `scope` attribute to `th` cells

Currently the mobile navigation isn't visible on the devices I used for testing so I left everything related to that open. I'll try a couple of non-navigation things this weekend 😄

**Comment by anneke** [comment]
A lot of this is covered by #282 so I'll close this one! We have some things to do still on the navigation but we're getting there!
