### ISSUE TITLE
Fix audit issues for navigation

### ISSUE THREAD

**Issue by SleeplessByte** [fronteers/website#282]
**Describe the bug**
Split of from #273

**Comment by maniflames** [comment]
Heya sorry for the wait! I think I have found everything within the audit related to navigation. The mobile navigation isn't triggered on the devices I tested with so I left everything related to mobile navigation open. 

The TODOs for this ticket based on the [issues only report](https://www.toegankelijkheidscertificaat.nl/fronteers.nl/audit/issues/) of the audit are: 
- [ ] Finding 1: (optional?) Turn names of socials in the footer into `h3` elements
- [ ] Finding 5: Ensure selected pages in navigation submenu have an additional visual indicator for those who are colorblind
- [x] Finding 7: The 'join us' button disappears from a 200% zoom and has no alternative
- [x] Finding 9: The navbar doesn't allow for keyboard navigation
- [ ] Finding 10: Ensure that the navigation at a 400% zoom doesn't disappear when transitioning from open to closed. Optionally put focus on first menu item when menu is opened.
- [ ] Finding 12: Ensure that the navigation button at a 400% zoom has a visible focus state
- [x] Finding 13: Ensure that the correct language is used for visually hidden text in the language switcher
- [ ] Finding 14: (optional/not needed for WCAG 2.2 A compliance) Ensure there is only one element with the id "Icon_menu"
- [ ] Finding 15: Ensure that spans end with an additional space in visually hidden text in the language switcher
- [x] Finding 16: Ensure that selected pages that are linked in the footer are marked as active through aria-current
- [ ] Finding 17: Ensure that the navigation button at a 400% zoom only has one button for opening and closing the menu. Use aria-expanded to notify the user that the menu is open or closed.
