### ISSUE TITLE
Upgrade Eleventy / Vite

### ISSUE THREAD

**Issue by anneke** [fronteers/website#295]
<img width="1266" alt="Scherm­afbeelding 2024-01-05 om 18 40 19" src="https://github.com/fronteers/website/assets/7202272/e563c508-b97a-481e-9c24-3571ae2365ce">

During a (local) build we get the above error message. This is blocking and should be fixed

**Comment by SleeplessByte** [comment]
@anneke if you temporarily remove https://github.com/fronteers/website/tree/main/patches the build should not yield this error. I have not checked if the patches from those folders have been applied to the actual packages.

**Comment by anneke** [comment]
Because we kept running into problems I cloned `main` into a `main-not-working` branch (I didn't see your comment before) and reverted the addition of Vite to at least get closer to finishing this thing. I will look at this again later :)
