### ISSUE TITLE
Document workflow "Create a component"

### ISSUE THREAD

**Issue by michaelhastrich** [fronteers/website#30]
Document the steps needed to create a new component for the Fronteers website.

- [x] write documentation in form of a `CONTRIBUTE.md` file
- [x] check with eachother if text is clear
- [ ] translate in English/Dutch

**Comment by anneke** [comment]
Added documentation (in English) with a listing of all the frontmatter options:

https://github.com/fronteers/website/blob/main/docs/how-to-add-content.md

Will add documentation on where everything currently is :)

**Comment by anneke** [comment]
I would suggest we keep English as default language so no translation to Dutch would be necessary!
