### ISSUE TITLE
Add content on missing pages / migrate additional pages

### ISSUE THREAD

**Issue by maniflames** [fronteers/website#311]
**Description**
There are a couple of pages that don't have any content yet. Additionally @anneke noticed some pages that have not been migrated yet while working on the site redirects. Blank pages I have been able to identify are:

- [ ] /en/footer/contact/
- [ ] /nl/footer/privacy-en-cookies/
- [ ] /en/footer/privacy-and-cookies/
- [ ] /nl/footer/colofon/
- [ ] /en/footer/colophon/
- [ ] /nl/footer/adverteren/
- [ ] /en/footer/advertise/

**Comment by anneke** [comment]
I suggest for the colophon we make a list of the people that have worked on the website. Adverteren is a "business choice" I think for the board to discuss. /en/footer/contact should link to /en/contact I think.

For the privacy and cookies page, I think the only thing really needed is to explain we don't set cookies, but maybe sometimes include third party things like maps or youtube/vimeo that might have trackers (and that we try to go for services that don't do these things)?

**Comment by edwinm** [comment]
About the cookies: I browsed the website and not a single cookie is set, So (for now) it's safe to claim no cookies are set (and we don't need a cookie confimation dialog).

**Comment by edwinm** [comment]
I'm removing the Advertise link for now.

**Comment by edwinm** [comment]
The privacy/cookie statement is quite terse now. We might need to have somebody more legal savvy to take a look. Or use a generic one and adjust for our situation (we don't use cookies).
