### ISSUE TITLE
Remove broken links

### ISSUE THREAD

**Issue by edwinm** [fronteers/website#314]
**Describe the bug**

During build, we now see broken links.

Remove these links from the content.

**Expected behavior**

During build, no broken links should be reported.

## Current state

[plugin-broken-links] Link is broken: http://www.webrichtlijnen.nl/
[plugin-broken-links] HTTP Status Code: ADDRESS NOT FOUND
[plugin-broken-links] Used 23 time(s) on these pages:
[plugin-broken-links]   - ./src/nl/activiteiten/2009/kees-tm.md
[plugin-broken-links] Link is broken: http://joggink.be/
[plugin-broken-links] HTTP Status Code: ADDRESS NOT FOUND
[plugin-broken-links] Used 46 time(s) on these pages:
[plugin-broken-links]   - ./src/nl/activiteiten/2011/phl.md
[plugin-broken-links]   - ./src/nl/blog/2011/03/bijeenkomst-hasselt.md
[plugin-broken-links] Link is broken: http://www1.lunatech.com/~egor/fep/
[plugin-broken-links] HTTP Status Code: ADDRESS NOT FOUND
[plugin-broken-links] Used 23 time(s) on these pages:
[plugin-broken-links]   - ./src/nl/activiteiten/2011/lunatech-research.md

**Comment by edwinm** [comment]
More links left:

[plugin-broken-links] Link is broken: http://www.mindz.com/plazas/Seats2meet_com_Utrecht/pages/Routebeschrijving_en_contact
[plugin-broken-links] HTTP Status Code: 404
[plugin-broken-links] Used 9 time(s) on these pages:
[plugin-broken-links]   - ./src/nl/workshops-archief/future-css-bert-bos/28-januari-2013.md
[plugin-broken-links]   - ./src/nl/workshops-archief/css-positionering-peter-paul-koch.md
[plugin-broken-links]   - ./src/nl/workshops-archief/counter-space-jeroen-visser.md
[plugin-broken-links]   - ./src/nl/workshops-archief/javascript-achtbaan-peter-van-der-zee.md
[plugin-broken-links]   - ./src/nl/workshops-archief/praktisch-html5-peter-beverloo.md
[plugin-broken-links]   - ./src/nl/workshops-archief/jquery-inception-arjan-eising.md
[plugin-broken-links]   - ./src/nl/workshops-archief/rabid-prototyping-stephen-hay.md
[plugin-broken-links]   - ./src/nl/workshops-archief/screw-css-roy-tomeij.md
[plugin-broken-links]   - ./src/nl/workshops-archief/viewports-peter-paul-koch.md
[plugin-broken-links] Link is broken: http://www.waalweb.nl/
[plugin-broken-links] HTTP Status Code: ADDRESS NOT FOUND
[plugin-broken-links] Used 1 time(s) on these pages:
[plugin-broken-links]   - ./src/nl/workshops-archief/html-css-frances-de-waal.md
[plugin-broken-links] Link is broken: http://www.waalweb.nl
[plugin-broken-links] HTTP Status Code: ADDRESS NOT FOUND
[plugin-broken-links] Used 2 time(s) on these pages:
[plugin-broken-links]   - ./src/nl/workshops-archief/responsive-design-frances-de-waal.md
[plugin-broken-links]   - ./src/nl/workshops-archief/mobiel-web-frances-de-waal.md

**Comment by SleeplessByte** [comment]
Should be none left since #330

**Comment by anneke** [comment]
There was one left (maybe new), I will make a PR fixing that one (It's meetup.com that probably deleted a page between the last comment and today)
