### ISSUE TITLE
Language switch component

### ISSUE THREAD

**Issue by michaelhastrich** [fronteers/website#33]
Initially the website will support Dutch and English.

Requirements:
- Switching between languages should redirect the user to the desired language.

## Status of the build checklist

- [x] the design has been turned into HTML and CSS
- [x] the CSS is well-organised and cleaned up from development
- [x] the HTML is semantic and passes an automated accessibility test
- [x] the component is no longer scaffolding but easy to use in the setup of other pages
- [x] the work done is represented to kitchensink and kitchensink-html for documentation
- [x] the work done is added to the `component` folder as a block or as a shortcode
- [x] the work done has been commented or is (really!) self-explanatory

**Comment by anneke** [comment]
```
    {% include partials/page-header/translate %}
```

**Comment by anneke** [comment]
Some of the documentation for this is currently in https://github.com/fronteers/website/blob/main/docs/how-to-add-content.md , will use this to document this code better.
