### ISSUE TITLE
Navigation component

### ISSUE THREAD

**Issue by michaelhastrich** [fronteers/website#36]
This component contains the main site navigation.

Requirements:
TBD

## Status of the build checklist

- [x] the design has been turned into HTML and CSS
- [x] the CSS is well-organised and cleaned up from development
- [x] the HTML is semantic and passes an automated accessibility test
- [x] the component is no longer scaffolding but easy to use in the setup of other pages
- [x] the work done is added to the `component` folder as a block or as a shortcode
- [x] the work done is represented to kitchensink and kitchensink-html for documentation
- [x] the work done has been commented or is (really!) self-explanatory

**Comment by anneke** [comment]
Kreeg dit niet werkend als shortcode of paired shortcodes, maar wel als include:

```
{% include partials/navigation where:"header" description:"Main navigation" toplevelloop:header_navigation sublevelloop:header_sub_navigation %}
```
