### ISSUE TITLE
Make it clearer which language is selected

### ISSUE THREAD

**Issue by bnijenhuis** [fronteers/website#372]
It's not really clear which language is selected (EN is bold, but it's not the language that is selected). And the headings are a mix between Dutch and English.

![Language selection](https://github.com/user-attachments/assets/87dcad55-e266-476b-8e38-c5a178bbf52a)
![Heading overview](https://github.com/user-attachments/assets/99f9fc16-0ecc-4a25-b2c5-4bcdbf71de2d)

**Comment by anneke** [comment]
I fixed the English copy, but the design of the language toggle needs someone with more design skills than me! Any ideas @bnijenhuis ? :)

**Comment by TinekeinTOWN** [comment]
@anneke I might be able to help (but haven't helped with this website before)?

**Comment by bnijenhuis** [comment]
@anneke @TinekeinTOWN I'm no designer too (for proof you can visit my website :P), but I don't think it's clear enough yet. The language that is not selected is bold and underline now (which to me just looks more selected, because the navigation hover effect is bold, yellow and underlined). So maybe switching it around will help?

**Comment by anneke** [comment]
![Scherm­afbeelding 2024-10-20 om 18 30 36](https://github.com/user-attachments/assets/56ff662f-a40c-4ebb-a89c-c0a328a6fee5)
![Scherm­afbeelding 2024-10-20 om 18 30 44](https://github.com/user-attachments/assets/b5851208-fdf5-43df-9567-625318dc9f67)
![Scherm­afbeelding 2024-10-20 om 18 30 50](https://github.com/user-attachments/assets/0cf65221-5c0b-4f57-b8ec-ae35dba2173e)

What do you think of this, just changing it to the language you're not currently on? @TinekeinTOWN opinions are very welcome!

**Comment by TinekeinTOWN** [comment]
@bnijenhuis @anneke 
If I look at some designs present this is what I see it should be:

The current / active language should be **bold** + yellow.
The unselected / not current language should be regular + white.
I would add an underline to the unselected language to make it more clear. 

If wanted/needed I could make an (accessible) language toggle, but I think the above should already fix it.

**Comment by TinekeinTOWN** [comment]
@anneke Ha, both at the same time :-) It's a nice solution. But not sure if with just one language present it's fully clear?

**Comment by anneke** [comment]
I'll first follow your suggestion and I'll post some screenshots :)

**Comment by anneke** [comment]
![Scherm­afbeelding 2024-10-20 om 18 45 30](https://github.com/user-attachments/assets/44c3894e-ab5d-4e83-ae7d-d52d8fb3e1a1)

**Comment by Rosita311** [comment]
I am no designer either. Personaly I find the underline confusing. I think a button or toggle would be more clear. But I like this, more, it's more clear. 

> ![Scherm­afbeelding 2024-10-20 om 18 30 36](https://private-user-images.githubusercontent.com/7202272/378206140-56ff662f-a40c-4ebb-a89c-c0a328a6fee5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk0NDg0NTEsIm5iZiI6MTcyOTQ0ODE1MSwicGF0aCI6Ii83MjAyMjcyLzM3ODIwNjE0MC01NmZmNjYyZi1hNDBjLTRlYmItYTg5Yy1jMGEzMjhhNmZlZTUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMjBUMTgxNTUxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTAwNDZiZGU2MmVlNjcyZDIzNTdhNzNiMDg2NjQ1YWRhZmY5YTgxNjVmYWVlNGZlMTA4YTFjM2NlMWMwMzg1NCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.A7yvVHPc0MilOaWzh6fJ7v5yAqwx2d1bkuGy7XPBwRM) ![Scherm­afbeelding 2024-10-20 om 18 30 44](https://private-user-images.githubusercontent.com/7202272/378206143-b5851208-fdf5-43df-9567-625318dc9f67.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk0NDg0NTEsIm5iZiI6MTcyOTQ0ODE1MSwicGF0aCI6Ii83MjAyMjcyLzM3ODIwNjE0My1iNTg1MTIwOC1mZGY1LTQzZGYtOTU2Ny02MjUzMThkYzlmNjcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMjBUMTgxNTUxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjQ5OTVlYTIzYTEwYzg5NWFjZmFlOTJhM2RiNDAyNzc0OTczMjNkN2I4OWMyNmViZDhmMDU4MWIyNjhkOTdlMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.5bEoXb420_7Fk9WDLikBNdE4eIMy7hk6XI_yiDumh7M) ![Scherm­afbeelding 2024-10-20 om 18 30 50](https://private-user-images.githubusercontent.com/7202272/378206144-0cf65221-5c0b-4f57-b8ec-ae35dba2173e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk0NDg0NTEsIm5iZiI6MTcyOTQ0ODE1MSwicGF0aCI6Ii83MjAyMjcyLzM3ODIwNjE0NC0wY2Y2NTIyMS01YzBiLTRmNTctYjhlYy1hZTM1ZGJhMjE3M2UucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMjBUMTgxNTUxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZGYzOTJlMDk3MDc2ZjM0MzhkMmViYmU4ODUwNGI4YTA3YjhjYWYzMzU4YTVmMGQyNTUzYThhOTUxYmFjYzhkNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.yDHY3NBBo2aP7W8gPMTqefHRqA8nnHz39z4B-Qb5R4g)
> 
> What do you think of this, just changing it to the language you're not currently on? @TinekeinTOWN opinions are very welcome!

**Comment by Rosita311** [comment]
Now I see another change, which I like most. Now it's clear to me that the active language is Dutch
<img width="95" alt="image" src="https://github.com/user-attachments/assets/6cdffe28-0de4-4d79-9441-28f43c639461">

**Comment by anneke** [comment]
Okay! Let's go with the last idea then (Tineke's suggestion) :)
