### ISSUE TITLE
🏗 Component: Social media links

### ISSUE THREAD

**Issue by michaelhastrich** [fronteers/website#38]
These are the small blocks of content that link to the specific social media channels, ie Slack etc.

Requirements:
- Contains a short description of the content on the specific channel
- Contains a link to the specific channel
- Is able to contain a logo of the specific channel

## Status of the build checklist

- [x] the design has been turned into HTML and CSS
- [ ] the component is responsive
- [x] the CSS is well-organised and cleaned up from development
- [x] the HTML is semantic and passes an automated accessibility test
- [ ] the component is no longer scaffolding but easy to use in the setup of other pages
- [ ] the work done is added to the `component` folder as a block or as a shortcode
- [ ] the work done is represented to kitchensink and kitchensink-html for documentation
- [ ] the work done has been commented or is (really!) self-explanatory

**Comment by AnnemiekNieboer** [comment]
@michaelhastrich of @anneke ik zie al social logo's in de footer staan, voorzien van een tekst en ze hebben een link naar het juiste social kanaal. Moet hier nog wat aan aangepast worden of kan deze geclosed worden?

**Comment by AnnemiekNieboer** [comment]
Was al klaar
