### ISSUE TITLE
Check content

### ISSUE THREAD

**Issue by anneke** [fronteers/website#388]
@Rosita311 made a list:

- Info updaten op de pagina's:
    - [ ] Commissies
    - [x] Geschiedenis
    - [x] Ook alle info mbt Twitter.
- [x] Op de pagina met de leden mist een hero met een titel en een korte intro.
- [x] Op de pagina Freelance sta jij (Anneke) als enige freelancer, klopt dat? Lijkt me niet. (_Anneke: Pagina onzichtbaar/onbereikbaar gemaakt voor nu_)
Meetups pagina is leeg. Misschien samenvoegen met Activiteiten of workshops?
- [x] Alleen de individuele blogs en de drie pagina's Meetups, Workshop archief en video archief hebben een "edit this page on GitHub" link (_Anneke: Meer pagina's hebben de link, maar zal het langslopen_)

**Comment by SleeplessByte** [comment]
Zijn er paginas die we uiteindelijk NIET hebben overgeheveld? Die moeten een 410 krijgen in redirects file :)

**Comment by anneke** [comment]
Ja, die staan in not-redirected.txt in de root! Allemaal congrespagina's.
