### ISSUE TITLE
🏗 Component: Join Us (footer block)

### ISSUE THREAD

**Issue by michaelhastrich** [fronteers/website#39]
This contains a short appealing text and a link to the registration form. Please check and judge if this component and the "Join Us" component in the header could/should be combined.

![Example of the design for the join us-footer block](https://github.com/fronteers/website/blob/main/designs/join-us-footer.png?raw=true)

## Design
You can find the component appear in [the design for the about us page](hhttps://xd.adobe.com/view/bd533314-bf05-4cbe-b634-499f8f25dbbc-e800/screen/bd345fab-b868-4180-8bb3-05f62375d54d/)

## Files to edit: 

[join-us.liquid](https://github.com/fronteers/website/blob/main/src/_includes/partials/page-footer/_page-footer.liquid#L37-L41)
[join-us.css](https://github.com/fronteers/website/blob/main/src/_includes/partials/page-footer/_page-footer.css#L89-L104) 

In the header:
[join-us.liquid](https://github.com/fronteers/website/blob/main/src/_includes/partials/page-header/join-us.liquid)
[join-us.css](https://github.com/fronteers/website/blob/main/src/_includes/partials/page-header/join-us.css)

In the footer:
[page-footer.liquid](https://github.com/fronteers/website/blob/main/src/_includes/partials/page-footer/_page-footer.liquid)
[page-footer.css](https://github.com/fronteers/website/blob/main/src/_includes/partials/page-footer/_page-footer.css)

## Status of the build checklist

- [x] the design has been turned into HTML and CSS
- [ ] the CSS is well-organised and cleaned up from development
- [x] the HTML is semantic and passes an automated accessibility test
- [ ] the component is no longer scaffolding but easy to use in the setup of other pages 
- [ ] make content editable through markdown
- [ ] the work done is added to the `component` folder as a block or as a shortcode
- [ ] the work done is represented to kitchensink and kitchensink-html for documentation
- [ ] the work done has been commented or is (really!) self-explanatory

**Comment by anneke** [comment]
We could set a default for the content of the footer through frontmatter somewhere, and then overwrite the frontmatter on pages where we would want the content to be different

**Comment by AnnemiekNieboer** [comment]
Iov met @michaelhastrich kan gesloten worden
