### ISSUE TITLE
English language switch on the homepage isn't working

### ISSUE THREAD

**Issue by banaan666** [fronteers/website#391]
When visiting https://fronteers.netlify.app, if you visit on the EN link at the top right (Desktop) you end up on https://fronteers.netlify.app instead of https://fronteers.netlify.app/en/

**To Reproduce**
1. Go to '[https://fronteers.netlify.app](https://fronteers.netlify.app)'
2. Click on 'EN'
3. Look at the addressbar of the browser
4. It shows https://fronteers.netlify.app

**Expected behavior**
Addressbar should show https://fronteers.netlify.app/en

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Firefox
 - Version: 131.0.3

**Comment by anneke** [comment]
Should be fixed by @SleeplessByte 's last pull requests!
