### ISSUE TITLE
Number of members on https://fronteers.nl/nl/leden/ doesn't include hidden members but does include the empty EOF record.

### ISSUE THREAD

**Issue by banaan666** [fronteers/website#396]
**Describe the bug**
We have a few members that don't want to be shown on the website... how can we include them in the count?

**To Reproduce**
1. Go to 'https://fronteers.nl/nl/leden/'
2. See the text showing "Op dit moment heeft Fronteers 147 leden." 

**Expected behavior**
This should be: "Op dit moment heeft Fronteers 151 leden."

So number should be: COUNT(JSON)-1 + HIDDEN_MEMBERS(5)

**Desktop (please complete the following information):**

**Additional context**

**Comment by banaan666** [comment]
That's a nice quick solution Anneke! Smart move

**Comment by anneke** [comment]
Thank you 🙏
