### ISSUE TITLE
Werk en Freelance produces a 404 page

### ISSUE THREAD

**Issue by sanjaytwisk** [fronteers/website#408]
**Describe the bug**
When trying to visit the "Werk en Freelance" page from the main navigation the destination page displays a 404 message.

**To Reproduce**
1. Go to the homepage
2. Click on "Werk en Freelance" in the main navigation

**Expected behavior**
A page that contains content about "Werk en Freelance"

**Screenshots**
<img width="1289" alt="image" src="https://github.com/user-attachments/assets/72c5594e-026c-475c-b01a-c5ff3fee58fb">

**Desktop (please complete the following information):**
 - OS: macOS
 - Brave
 - Version 1.70.119 Chromium: 129.0.6668.70 (Official Build) (arm64)

**Comment by michaelhastrich** [comment]
Was fixed by this [PR](https://github.com/fronteers/website/pull/415)
