### ISSUE TITLE
Use absolute paths rather than relative paths with the rel="canonical" link element.

### ISSUE THREAD

**Issue by DanielleCuppen** [fronteers/website#412]
**Describe the bug**
Use absolute paths rather than relative paths with the rel="canonical" link element. Even though relative paths are supported by Google, they can cause problems in the long run.

**To Reproduce**
1. Test website on https://pagespeed.web.dev/
2. Click on 'SEO'
3. See 'Practical tips for content indexing' (score 85) 
4. View source homepage:
link rel="canonical" href="/"
link rel="alternate" hreflang="nl-NL" href="/"
link rel="alternate" hreflang="en-US" href="/en/"

**Expected behavior**
link rel="canonical" href="https://www.fronteers.nl/"
link rel="alternate" hreflang="nl-NL" href="https://www.fronteers.nl/nl/"
link rel="alternate" hreflang="en-US" href="https://www.fronteers.nl/en/"

**Additional context**
Should be a 100% SEO score when using absolute paths.

**Comment by SleeplessByte** [comment]
Done in https://github.com/fronteers/website/commit/e1560eec00ff9f72b92d54e7f8f09048ec79c865

Was meant to be absolute!

**Comment by DanielleCuppen** [comment]
Top!
