### ISSUE TITLE
Use forms instead of preformatted mail link for job positions and members

### ISSUE THREAD

**Issue by bnijenhuis** [fronteers/website#429]
## Description
I'd prefer a form over a preformatted mail link for subscribing as a member and for placing a job position.

## Why should we include this?
Mail links open in the default mail client (which isn't always in use, because for instance I use gmail, but the link tries to open the Mail app). That's a barrier. Furthermore it forces the user to enter certain information, whereas a preformatted mail can easily be emptied and replaced with my own content.

## Happy flow
Show form with fixed (required) fields for subscribing as a member and for placing a job position.

## Additional context
I know this is a static website and we're using Eleventy, but there must be solutions for this.

**Comment by anneke** [comment]
@claudia-rndrs didn't you have a platform for forms, like Google Forms but a little nicer? Maybe that's a good in-between-solution? Otherwise Eleventy Forms perhaps.

**Comment by anneke** [comment]
Ah, using Netlify forms should be as easy as adding a `netlify` keyword in a form tag. I'll try it in my open PR!
 
@bnijenhuis

**Comment by claudia-rndrs** [comment]
@anneke @bnijenhuis  I already started making a form a few months ago, but I ran into difficulties with rendering it and then it got too busy at work for me to continue.
But I still have it saved locally! I will see if I can add it to the latest version of the website and make a draft PR.

In case  we would need an alternative to google forms, I would highly recommend using [tally forms](https://tally.so)

**Comment by anneke** [comment]
@claudia-rndrs I've got a form working that will collect send-ins on Netlify and can mail the appropriate person/committee directly! So I would say that'll work fine for now :) 

Check out https://www.fronteers.nl/nl/werk-en-freelance/vacature-plaatsen/formulier.html (I've tested it, and it works)
