### ISSUE TITLE
Dropdown menus are not accessible enough

### ISSUE THREAD

**Issue by SleeplessByte** [fronteers/website#436]
**Describe the bug**

Keyboard shortcuts are missing, too many tab-stops.

**To Reproduce**

1. Go to https://www.fronteers.nl/
2. Tab onto Over **Fronteers**
3. Press down (nothing happens)
4. Tab again onto the expand
5. Press down (nothing happens)
6. Press enter
7. Press down (nothing happens)

**Expected behavior**

- [x] Down should select the first item in the list
- [x] Up should select the last item in the list
- [x] Opening the menu should move the focus (it does not)
- [x] Each item should be accessible using arrow keys and be a single tab-stop
- [x] Optional: blurring the menu (tabbing out of it) should close it
- [ ] Optional: if the submenu is a single tab stop, it can be opened on focussing the dropdown arrow (because tab will close it again)
- [ ] Bonus: the `open` class is unnecessary. `[aria-expanded="true"]` can be used to flip the icon. `[aria-expanded="true"] + ul` can be used to show the menu in mobile mode.

**Comment by SleeplessByte** [comment]
@anneke huge improvements already!

- [] up on closed menu should open the last item in the list
- [] right to left navigation should not go to the footer menu (so congres should not go to contact and contact should not go to congres)
- [] right / left on a submenu should NOT select the first item in the list, but rather the "main" item. Right now you need to SHIFT + TAB to get out of the menu
- [] escape to close works well, but you can then no longer press down/up to reopen the menu. This is probably because the focus is moved to either the incorrect element or that element doesn't also listen for the keyboard events.

**Comment by anneke** [comment]
Thank you for the feedback @SleeplessByte ! Will tackle this later.

**Comment by anneke** [comment]
I have taken this on board, buuut I am still thinking how a user would know they can use arrow keys. Plus we're not telling them with aria-controls or aria-expanded on the link that somehow they can open the menu.
