### ISSUE TITLE
Branch deployments fail because the build takes too long

### ISSUE THREAD

**Issue by maniflames** [fronteers/website#464]
**Describe the bug**
While reviewing #450 we noticed the Netlify build did not succeed due to the long build time of the site. Although changes are visible on the production site after the pull request has been merged it might be nice to be able to preview branch deployments. It might be interesting to see whether we can add an additional build command that leans on 11ty's [incremental builds](https://www.11ty.dev/docs/usage/incremental/).

**To Reproduce**
1. Clone this repo and create a new branch
2. Create a pull request to trigger 
3. Wait for the Netlify build to start 
4. Go to the logs to view the results

**Expected behavior**
Whenever a new pull request is created Netlify is able to build & deploy a preview.

**Additional context**
Example build log of failing deployment: [feature/remove-balloons](https://github.com/fronteers/website/tree/feature/remove-balloons)](https://app.netlify.com/sites/fronteers/deploys/671e47fb16a12500088f0ded)

**Comment by SleeplessByte** [comment]
We are already using eleventy's incremental build system in development. I don't think it will be easy to set up for the netlify builds as you cannot store artifacts inbetween, nor would you usually want to. Changing a layout for example should trigger a full rebuild.

Instead, you probably want to increase the limit as described [on the Netlify forum](https://answers.netlify.com/t/support-guide-how-to-use-the-api-to-increase-your-sites-build-time-limit/52805#p-145650-how-do-i-change-the-build-time-limit-3).

The default limit is 15min. We probably can work with 20min for a long time. When I started working on this a few years ago it was ~13.5min.

**Comment by maniflames** [comment]
Ahh I definitely didn't take into account that Netlify CI doesn't support artifacts in between builds. In that case incremental builds won't do anything at all. 

Unfortunately I don't have access to the fronteers Netlify account. Should I add the 'Fronteers Board' label?
