### ISSUE TITLE
Friendly, minimal analytics

### ISSUE THREAD

**Issue by JoseeWouters** [fronteers/website#6]
## Description
We should investigate which Analytics tool we want to use and implement this. We probably do not want to integrate Google Analytics, but a less intrusive tool.

## Why should we include this?
We want to know how many visitors we have and what the most popular pages are.

## Additional context
Whoever starts implementing this, should work together with the marketing committee. (Koen, Tom or @JoseeWouters)

**Comment by anneke** [comment]
I suggest Plausible, super easy to put in there, AVG/GDPR compliant and you can share a public link to the analytics which is nice: https://plausible.io/forum-downloader.annekesinnema.nl

**Comment by Mangamaui** [comment]
Maybe Fathom is also worth checking out as an viable option? It is also GDPR complient, privacy-focused and has the ability to publicly share analytics,...

https://usefathom.com/

I've been using it for a year now and so far no complaints. 😊

**Comment by anneke** [comment]
I've looked into Fathom to compare it with Plausible, and they seem to be virtually the same (they both have the pluses mentioned above for Fathom) but Plausible is cheaper until we exceed 10K pageviews per month. 

I think we'll start out with Plausible and if we exceed it we can go to UseFathom.
