### ISSUE TITLE
🏗  Component: Styling of filters for blogs, jobs, members, activities, freelancers

### ISSUE THREAD

**Issue by anneke** [fronteers/website#76]
![Example of the design for the activity filters](https://github.com/fronteers/website/blob/main/designs/activityfilters.png?raw=true)

Here you see an example of what filtering can look like. Filtering can be applied on blogs, jobs, members, activities and freelancers' specialties. 

You can find an example of the design here: [the filters design](https://xd.adobe.com/view/bd533314-bf05-4cbe-b634-499f8f25dbbc-e800/screen/80794413-e742-46cb-864b-6c25aaf82252/).
[The design for the filters on the 'activities' page](https://xd.adobe.com/view/bd533314-bf05-4cbe-b634-499f8f25dbbc-e800/screen/f38cbe49-ff62-428b-8bb0-c6c29d831bac/)

## Files to edit: 
- [loop-activity-categories.liquid](https://github.com/fronteers/website/blob/main/src/_includes/partials/activities/loop-activity-categories.liquid)
- [loop-activity-categories.css](https://github.com/fronteers/website/blob/main/src/_includes/partials/activities/loop-activity-categories.css)

The same, but different loops, exist for blogs, freelancers, and jobs. 
Maybe you will only need to style this once, and apply it everywhere (and maybe, figure out how we can make our code more dry?)

- [loop-jobs-categories.liquid](https://github.com/fronteers/website/blob/main/src/_includes/partials/jobs/loop-jobs-categories.liquid)
- [loop-jobs-categories.css](https://github.com/fronteers/website/blob/main/src/_includes/partials/jobs/loop-jobs-categories.css)
 - [loop-blog-categories.liquid](https://github.com/fronteers/website/blob/main/src/_includes/partials/blog/loop-blog-categories.liquid)
- [loop-blog-categories.css](https://github.com/fronteers/website/blob/main/src/_includes/partials/blog/loop-blog-categories.css)
- [loop-freelancers-specialties.liquid](https://github.com/fronteers/website/blob/main/src/_includes/partials/freelancers/loop-freelancers-specialties.liquid)
- [loop-freelancers-specialties.css](https://github.com/fronteers/website/blob/main/src/_includes/partials/freelancers/loop-freelancers-specialties.css)

## Loosely connected files:
- [activity-category.liquid](https://github.com/fronteers/website/blob/main/src/_includes/layouts/activity-category.liquid)
- [activity-home.liquid](https://github.com/fronteers/website/blob/main/src/_includes/layouts/activity-home.liquid)
- [blog-category.liquid](https://github.com/fronteers/website/blob/main/src/_includes/layouts/blog-category.liquid)
- [blog-home.liquid](https://github.com/fronteers/website/blob/main/src/_includes/layouts/blog-home.liquid)
- [jobs-category.liquid](https://github.com/fronteers/website/blob/main/src/_includes/layouts/jobs-category.liquid)
- [jobs-home.liquid](https://github.com/fronteers/website/blob/main/src/_includes/layouts/jobs-home.liquid)
- [freelancers-category.liquid](https://github.com/fronteers/website/blob/main/src/_includes/layouts/freelancers-category.liquid)
- [freelancers-home.liquid](https://github.com/fronteers/website/blob/main/src/_includes/layouts/freelancers-home.liquid)

In these files, we call the "loop all the X categories" include with, as an example:
```
{% include partials/activities/loop-activity-categories %}
```

## Status of the build checklist

- [x] the design has been turned into HTML and CSS
- [x] the component is responsive
- [x] the CSS is well-organised and cleaned up from development
- [ ] the HTML is semantic and passes an automated accessibility test
- [ ] the component is no longer scaffolding but easy to use in the setup of other pages
- [x] the work done is added to the `component` folder as a block or as a shortcode, if it makes sense to in future use this component within articles and running text
- [ ] the work done is represented to `src/nl/kitchensink` or `src/nl/kitchensink-html` for documentation
- [x] the work done has been commented or is (really!) self-explanatory

**Comment by AnnemiekNieboer** [comment]
@mserykh can you give an update about this issue?
