### ISSUE TITLE
🏗  Component: "About Fronteers" page hero/header

### ISSUE THREAD

**Issue by anneke** [fronteers/website#77]
![Example of the design for the about-us header](https://github.com/fronteers/website/blob/main/designs/aboutusheader.png?raw=true)

Variant of src/_includes/partials/homepage/home-hero.liquid. Take a look at that one, to see if it's more recent/better, or 
if it could benefit from anything you learned here :-)  

You can find the design here: [the design for the about-us page](https://xd.adobe.com/view/bd533314-bf05-4cbe-b634-499f8f25dbbc-e800/screen/bd345fab-b868-4180-8bb3-05f62375d54d/)

Files to edit: 
[about-us-hero.liquid](https://github.com/fronteers/website/blob/main/src/_includes/partials/about-us/about-us-hero.liquid)
[about-us-hero.css](https://github.com/fronteers/website/blob/main/src/_includes/partials/about-us/about-us-hero.css)

## Status of the build checklist

- [x] the design has been turned into HTML and CSS
- [x] the component is responsive
- [x] the CSS is well-organised and cleaned up from development
- [x] the HTML is semantic and passes an automated accessibility test
- [x] the component is no longer scaffolding but easy to use in the setup of other pages
- [x] the work done is added to the `component` folder as a block or as a shortcode, if it makes sense to in future use this component within articles and running text
- [x] the work done is represented to `src/nl/kitchensink` or `src/nl/kitchensink-html` for documentation
- [x] the work done has been commented or is (really!) self-explanatory

**Comment by Ninajoy** [comment]
Created a PR :)

**Comment by Ninajoy** [comment]
https://github.com/fronteers/website/pull/146 is merged

**Comment by Ninajoy** [comment]
https://github.com/fronteers/website/pull/146 is merged so can close this issue
