### ISSUE TITLE
🏗  Component: Pagination

### ISSUE THREAD

**Issue by anneke** [fronteers/website#78]
![Example of the design for pagination](https://github.com/fronteers/website/blob/main/designs/pagination.png?raw=true)

Right now, our code supports a very simple pagination with `previous` and `next` links. Perhaps it's best to put temporary styling on it with the flavor of the design, and make a note to discuss this with Ready for Take-Off, our designers.
Add any notes and questions for them here: https://github.com/fronteers/website/issues/79 

Example of the design for pagination can be found here:
https://xd.adobe.com/view/bd533314-bf05-4cbe-b634-499f8f25dbbc-e800/screen/f38cbe49-ff62-428b-8bb0-c6c29d831bac/

Files to edit: 
[pagination.liquid](https://github.com/fronteers/website/blob/main/src/_includes/partials/pagination.liquid)
[pagination.css](https://github.com/fronteers/website/blob/main/src/_includes/partials/pagination.css)

## Status of the build checklist

- [x] the design has been turned into HTML and CSS
- [x] the component is responsive
- [x] the CSS is well-organised and cleaned up from development
- [x] the HTML is semantic and passes an automated accessibility test
- [ ] the component is no longer scaffolding but easy to use in the setup of other pages
- [ ] the work done is added to the `component` folder as a block or as a shortcode, if it makes sense to in future use this component within articles and running text
- [ ] the work done is represented to `src/nl/kitchensink` or `src/nl/kitchensink-html` for documentation
- [x] the work done has been commented or is (really!) self-explanatory

**Comment by michaelhastrich** [comment]
@anneke agree that we can close this issue?

**Comment by AnnemiekNieboer** [comment]
Toegepast en gemerged
