### ISSUE TITLE
🏗  Component: Get a taste of our conference banner

### ISSUE THREAD

**Issue by anneke** [fronteers/website#84]
![Example of the design for the join us-banner block](https://github.com/fronteers/website/blob/main/designs/conferencebanner.png?raw=true)

## Design
You can find the component appear in [the design for the about us page](https://xd.adobe.com/view/bd533314-bf05-4cbe-b634-499f8f25dbbc-e800/screen/bd345fab-b868-4180-8bb3-05f62375d54d/)

## Files to edit: 
[banner-conference.liquid](https://github.com/fronteers/website/blob/main/src/_includes/partials/homepage/banner-conference.liquid)
[banner-conference.css](https://github.com/fronteers/website/blob/main/src/_includes/partials/homepage/banner-conference.css)

## Status of the build checklist

- [ ] the design has been turned into HTML and CSS
- [ ] the component is responsive
- [ ] the CSS is well-organised and cleaned up from development
- [ ] the HTML is semantic and passes an automated accessibility test
- [ ] the component is no longer scaffolding but easy to use in the setup of other pages
- [ ] the work done is added to the `component` folder as a block or as a shortcode, if it makes sense to in future use this component within articles and running text
- [ ] the work done is represented to `src/nl/kitchensink` or `src/nl/kitchensink-html` for documentation
- [ ] the work done has been commented or is (really!) self-explanatory

**Comment by iflashlord** [comment]
I'd like to start working on this one.

**Comment by edwinm** [comment]
Great! You can assign this issue to yourself.

**Comment by iflashlord** [comment]
> Great! You can assign this issue to yourself.

I do not have permission to do that now

**Comment by iflashlord** [comment]
@anneke, can you permit me to edit the main issue for the checkboxes?

**Comment by edwinm** [comment]
@iflashlord This ticket is done, right?

**Comment by iflashlord** [comment]
Yes it is done, but I didn't have access to check the boxes in issue.

**Comment by edwinm** [comment]
@iflashlord Great, I'll close this issue.
