### ISSUE TITLE
🏗  Component: Fine-tune header navigation

### ISSUE THREAD

**Issue by anneke** [fronteers/website#85]
![Example of the design for the header navigation](https://github.com/fronteers/website/blob/main/designs/headernavigation.png?raw=true)
![Example of the design for the header navigation, when its opened]
(https://github.com/fronteers/website/blob/main/designs/openednavigation.png?raw=true)

It is working, and it looks a little like the design, but it needs a little bit of fine-tuning!

## Design
You can find the component appear in [the design for the about us page](https://xd.adobe.com/view/bd533314-bf05-4cbe-b634-499f8f25dbbc-e800/screen/bd345fab-b868-4180-8bb3-05f62375d54d/)

## Files to edit: 
[navigation.liquid](https://github.com/fronteers/website/blob/main/src/_includes/partials/navigation.liquid)
[navigation.css](https://github.com/fronteers/website/blob/main/src/_includes/partials/navigation.css)

## Issues found that should be fixed

- [x] Menu item texts wrap at point just before showing hamburger menu
- [x] Hamburger menu and language selector overlap
- [x] Sometime (to be specified), the menu bar dissapears
- [ ] Menu hover effect not as designed

## Status of the build checklist

- [x] the design has been turned into HTML and CSS
- [x] the CSS is well-organised and cleaned up from development
- [x] the HTML is semantic and passes an automated accessibility test
- [x] the component is no longer scaffolding but easy to use in the setup of other pages
- [x] the work done is added to the `component` folder as a block or as a shortcode, if it makes sense to in future use this component within articles and running text
- [x] the work done is represented to `src/nl/kitchensink` or `src/nl/kitchensink-html` for documentation
- [x] the work done has been commented or is (really!) self-explanatory

**Comment by edwinm** [comment]
The menu item hover effect is different from design.

Now it is: black background becomes lila background
Design is: Chevron and text become yellow and text under lined

@anneke Is this done on purpose, for accessibility reasons? Or should we still implement the design?
