### ISSUE TITLE
🏗  Component: Blog header/hero

### ISSUE THREAD

**Issue by anneke** [fronteers/website#87]
![Example of the design for the about-us header](https://github.com/fronteers/website/blob/main/designs/blogheader.png?raw=true)

Variant of src/_includes/partials/homepage/home-hero.liquid. Take a look at that one, to see if it's more recent/better, or 
if it could benefit from anything you learned here :-)  

You can find the design here: [the design for the blog page](https://xd.adobe.com/view/bd533314-bf05-4cbe-b634-499f8f25dbbc-e800/screen/eec3a419-36af-4c47-bff2-5b7af91160fc/)

Files to edit: 
[blog-hero.liquid](https://github.com/fronteers/website/blob/main/src/_includes/partials/blog/blog-hero.liquid)
[blog-hero.css](https://github.com/fronteers/website/blob/main/src/_includes/partials/blog/blog-hero.css)

## Status of the build checklist

- [ ] the design has been turned into HTML and CSS
- [ ] the component is responsive
- [ ] the CSS is well-organised and cleaned up from development
- [ ] the HTML is semantic and passes an automated accessibility test
- [ ] the component is no longer scaffolding but easy to use in the setup of other pages
- [ ] the work done is added to the `component` folder as a block or as a shortcode, if it makes sense to in future use this component within articles and running text
- [ ] the work done is represented to `src/nl/kitchensink` or `src/nl/kitchensink-html` for documentation
- [ ] the work done has been commented or is (really!) self-explanatory

**Comment by iflashlord** [comment]
I'd like to start working on this one.

**Comment by iflashlord** [comment]
I would like to pick this one. Could you please give me permission to assign and update issues?

**Comment by edwinm** [comment]
@iflashlord I assigned this ticket to you.

**Comment by anneke** [comment]
hi @iflashlord have you done any work on this? :) I noticed some other stuff you've done by the way on the homepage, very nice! Thank you :)

**Comment by iflashlord** [comment]
I will finish this one next week. Let me know if there is a specific plan or time limit.

**Comment by anneke** [comment]
Would be great Behrouz! No time limit as of yet, though it would be nice to really work towards finishing a first version together. I think next time we have a "meetup" set we can talk about it with the team and see if we can set a date/deadline :)

**Comment by iflashlord** [comment]
Finally! I have managed to work on this one. It also merged.

**Comment by edwinm** [comment]
Great!
