### ISSUE TITLE
Create a Fronteers flag generator

### ISSUE THREAD

**Issue by anneke** [fronteers/website#88]
In the branding guide of Fronteers, our designers came up with a fun concept: a flag system with which every member of Fronteers (or front-end developer) can generate their own flag. 

![Example of the design for the flags](https://github.com/fronteers/website/blob/main/designs/flagexamples.png?raw=true)

This could be built in a seperate folder, seperately from Eleventy, for us to put on a subdomain. But somehow it should generate something that is unique, that we can then use in a design like this:

![Example of the design for the flags](https://github.com/fronteers/website/blob/main/designs/memberquote.png?raw=true)

**Comment by anneke** [comment]
Woooooow @timseverien I never got a suggestion for this and this was in the middle of my mom being sick :( Thank you for this! It looks really good from the screenshots. Something to generate it would be awesome!

**Comment by timseverien** [comment]
I added another shortcode, `generateShield`, to compute a shield based on an arbitrary string:

<img width="964" alt="image" src="https://user-images.githubusercontent.com/2920299/205037913-5d63376a-0f5c-4be1-a7b7-26e9c81319c1.png">
