### ISSUE TITLE
🏗  Component: member quote block

### ISSUE THREAD

**Issue by anneke** [fronteers/website#89]
![Example of the design for the join us-banner block](https://github.com/fronteers/website/blob/main/designs/memberquote.png?raw=true)

## Design
[This element appears in a article page](https://xd.adobe.com/view/bd533314-bf05-4cbe-b634-499f8f25dbbc-e800/screen/1e3e266a-81bb-4368-857a-f499cd422560/). It also appears [on the about page](https://xd.adobe.com/view/bd533314-bf05-4cbe-b634-499f8f25dbbc-e800/screen/bd345fab-b868-4180-8bb3-05f62375d54d/)

## Files to edit: 
[member-quote.liquid](https://github.com/fronteers/website/blob/main/src/_includes/partials/about-us/member-quote.liquid)
[member-quote.css](https://github.com/fronteers/website/blob/main/src/_includes/partials/about-us/member-quote.css)

## Status of the build checklist

- [x] the design has been turned into HTML and CSS
- [x] the CSS is well-organised and cleaned up from development
- [x] the HTML is semantic and passes an automated accessibility test
- [x] the component is no longer scaffolding but easy to use in the setup of other pages
- [x] the work done is added to the `component` folder as a block or as a shortcode, if it makes sense to in future use this component within articles and running text
- [x] the work done is represented to `src/nl/kitchensink` or `src/nl/kitchensink-html` for documentation
- [x] the work done has been commented or is (really!) self-explanatory

**Comment by Ninajoy** [comment]
Just created the pr for adding the component
