### ISSUE TITLE
🏗  Component: a detail page

### ISSUE THREAD

**Issue by anneke** [fronteers/website#91]
When as a user you click through to a blog page, event page, or any other detail page, the result should look a little bit better than what it does now :) Luckily, we have a design for that!

[If you're running the website locally you can find an example here](http://localhost:8080/nl/blog/2020/12/anke-en-de-eerste-stapjes-in-het-land-van-drupal-theming.html). Otherwise [check out this page on the beta site on Netlify](https://deploy-preview-286--fronteers-beta.netlify.app/nl/blog/2020/12/anke-en-de-eerste-stapjes-in-het-land-van-drupal-theming.html)

## Design
[An article page](https://xd.adobe.com/view/bd533314-bf05-4cbe-b634-499f8f25dbbc-e800/screen/1e3e266a-81bb-4368-857a-f499cd422560/) and [an article mobile version](https://xd.adobe.com/view/bd533314-bf05-4cbe-b634-499f8f25dbbc-e800/screen/1ddf639f-ebf9-46d7-b187-25cb4cb1c7a6/)

## Files to edit: 
- [blog-single.liquid](https://github.com/fronteers/website/blob/main/src/_includes/layouts/blog-single.liquid)
- The [detailpage.css](https://github.com/fronteers/website/blob/main/src/_assets/css/common/detailpage.css)) is probably not in a good place, but putting styling here will work!
- Example blog markdown ("Article 9"): [2020-11-14.md](/https://github.com/fronteers/website/blob/main/src/nl/blog/2020/2020-11-14.md)

The biggest challenge will be how to make the content "flow around" the other blocks.
Perhaps with [Liquid capture](https://shopify.github.io/liquid/tags/variable/#capture) ? 

## Status of the build checklist

- [x] the design has been turned into HTML and CSS
- [x] the CSS is well-organised and cleaned up from development
- [x] the HTML is semantic and passes an automated accessibility test
- [x] the component is no longer scaffolding but easy to use in the setup of other pages
- [x] the work done is added to the `component` folder as a block or as a shortcode, if it makes sense to in future use this component within articles and running text
- [x] the work done is represented to `src/nl/kitchensink` or `src/nl/kitchensink-html` for documentation
- [ ] the work done has been commented or is (really!) self-explanatory

**Comment by anneke** [comment]
@edwinm have you done anything on this? :)

**Comment by edwinm** [comment]
No, feel free to pick this!

**Comment by anneke** [comment]
I have done some work on this as the example page shows, but it needs a check on code blocks to prevent them from overflowing, possibly a `overflow-x: scroll`
